### ISSUE TITLE
Support for primevideo.com

### ISSUE THREAD

**Issue by Sousa1988** [raynigon/AmazonAutoSkip#3]
It should be possible add support for https://www.primevideo.com site?

**Comment by raynigon** [comment]
I would like to, but unfortunately its not available in germany :/
Does it use the same video player?
If you could send me the class names, it should work after i added them.

Do you have more information about prime video as an external website?

**Comment by Sousa1988** [comment]
I tried adding the url "https://*.primevideo.com/*" to the manifest.json file and it works. So I guess it use the same video player.

primevideo.com it's the official site for Amazon Prime Video in Spain. If you access from amazon.es to Amazon Prime Video you will be redirected to primevideo.com

**Comment by raynigon** [comment]
I added the url and release the new version.
Please let me know if it worked and close the issue if so :)

**Comment by raynigon** [comment]
Firefox approved the extension, so it should work now
